# Generated by Django 3.1.4 on 2020-12-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('link', models.CharField(max_length=244)),
                ('thumbnail', models.CharField(max_length=244)),
                ('kind', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Supporter',
        ),
        migrations.AddField(
            model_name='user',
            name='donation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
