# Generated by Django 3.1.4 on 2020-12-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='history',
            name='thumbnail',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='link',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sound',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='play',
            name='link',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='thumbnail',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='link',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='thumbnail',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4FMgEe33BwCdnfLO89QdJEYxWMgc9I982fw&usqp=CAU', max_length=255),
        ),
    ]
