# Generated by Django 3.1.4 on 2020-12-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_try'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='photo',
            new_name='thumbnail',
        ),
    ]
