# Generated by Django 3.1.4 on 2020-12-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201213_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('donation', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='donation',
        ),
        migrations.AddField(
            model_name='play',
            name='category',
            field=models.CharField(default='x', max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(default='x', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(default='x', max_length=50),
        ),
    ]
