# Generated by Django 3.1.4 on 2020-12-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201215_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donation',
        ),
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donation',
            name='username',
            field=models.CharField(default='unknown', max_length=40),
        ),
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.CharField(default='picture', max_length=50),
        ),
        migrations.AlterField(
            model_name='play',
            name='category',
            field=models.CharField(default='game', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(default='video', max_length=50),
        ),
    ]
