# Generated by Django 3.1.4 on 2020-12-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201216_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='username',
            new_name='user',
        ),
    ]
